# Generated by Django 5.1.6 on 2025-03-06 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration): # Это появляется после 13) указывается как создать различные модели непосредственно в базе данных

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',   # Это появляется после 13) для category создаются различные поля (id создается автоматически)
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Curse',   # для Curse создаются различные поля (id создается автоматически)
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('students_qty', models.IntegerField()),
                ('reviews_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
