# Generated by Django 5.1.6 on 2025-03-07 06:25


# Это появляется после 15) Изменение в файле моделей (255 на 300)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),     # эта миграция зависит от миграции 0001, созданной на 13) и 14) пункте
    ]

    operations = [     # указывает, какие операции нужно выполнить
        migrations.AlterField(
            model_name='curse',
            name='title',
            field=models.CharField(max_length=300),     # это и есть изменение 255 на 300
        ),
    ]
